# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AppVK' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'Alamofire', '~> 5.4'

  # Pods for AppVK

  target 'AppVKTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'AppVKUITests' do
    # Pods for testing
  end

end
